### ISSUE TITLE
Can we integrate purplship for custom Local Courier service instead standard courier services like DHL, FedEX ?

### ISSUE THREAD

**Issue by lasanthaa** [PurplShip/purplship#76]
Hi,
Can i integrate purplship for custom Local Courier service  additional to standard built in ones in purplship ?

**Comment by DanH91** [comment]
Hi @lasanthaa,

Yes, you can the codebase is architected to allow some kind of plugins/extensions.
Unfortunately, it hasn't fully been documented yet.

I would love to help you with that actually.

In the meantime, https://github.com/PurplShip/purplship-extension/tree/main/purplship/eshipper is an example of an extension of additional services from a 3rd party.

**Comment by DanH91** [comment]
Hey @lasanthaa,

I got around to enriching the documentation and document the custom carrier integration process.
You can find it here: https://sdk.purplship.com/development/extending/
